### ISSUE TITLE
No se scrapean todos los artículos de Namespaces

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#100]
_From [dmascialino](https://code.google.com/u/dmascialino/) on April 06, 2011 10:51:28_

Como wikipedia no entrega un listado de todas las páginas en Namespaces, se utiliza el script listar_articulos_en_namespaces.py.
Este script recorre el listado /wiki/Especial:Todas buscando los links a los artículos, por ejemplo Categoría:Nacidos_en_1954 .
Luego scraper.py baja estos artículos.

El problema es que estos pueden estar divididos en varias páginas, en el ejemplo dado se muestran "las siguientes 200 páginas, de un total de 941".

(primera idea para) Solución:
Que listar_articulos_en_namespaces baje los artículos y corrobore (buscando si hay link a "siguiente" y "anterior") si tiene que bajar mas páginas, en caso de que sea así: bajarlas y modificar los nombres y los links que las apuntan.
Ejemplo:
En el caso mostrado, hay un link a: /index.php?title=Categor&#37;C3&#37;ADa:Nacidos_en_1954&pagefrom=D+ANGIO&#37;2CPINO&#37;0APINO+D&#37;27ANGI&#37;C3&#37;92 debe:
- guardar esta página como Nacidos_en_1954_2
- reemplazar el link en Nacidos_en_1954
- Ver si hay mas

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=99_

**Comment by facundobatista** [comment]
Tendríamos que entender al menos si esto sigue pasando

**Comment by macorv** [comment]
Los pasos para este caso seria:
- Verificar que en los casos que haya mas de 1 pagina de links solo se bajan los listados en la primer pagina únicamente.
- Si sigue pasando: 
  -- Diagramar y entender como es el flujo de trabajo de los scripts mencionados: `listar_articulos_en_namespaces.py` y `scraper.py`
  -- Entender cuál es el limite que se muestra por hoja y si existe algún parámetro en la URL que permita modificar ese limite.

**Comment by facundobatista** [comment]
Sí, verificar si sigue pasando. Si no, listo :)

Si sigue pasando, más allá de poder aumentar el límite, hay que implementar el poder pedir las N páginas subsiguientes. Creería que el problema está autocontenido en `listar_articulos_en_namespaces.py`.

**Comment by fzuccolo** [comment]
Esto está para cerrar, verifiqué que el problema descrito no existe actualmente.

El script `list_articles_by_namespaces.py` usa la API y maneja correctamente el parámetro `continue`.  En modo normal (no `--test-mode`) hace una lista con:  

| ns | nombre | páginas |
| ----: | ---- | ----: | 
| 14 | Categoría| 410.769 | 
| 12 | Ayuda |  395  |
| 104 | Anexo | 69.898 | 
| 100 | Portal | 16.630 |

**Comment by facundobatista** [comment]
Gracias
