### ISSUE TITLE
Sacar el boton de play de los media files incrustados

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#117]
_From [alecura](https://code.google.com/u/alecura/) on May 18, 2011 16:53:09_

Los .ogg de algunos artículos muestran el boton de play, pero traen el .ogg de la web

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=116_

**Comment by facundobatista** [comment]
Entendamos mejor en qué está esto ahora...

**Comment by fzuccolo** [comment]
Por ej. en el artículo *Argentina* [[cdpedia][1]/[wikipedia][2]] se ve el reproductor en la
InfoBox de la derecha para escuchar el Himno Nacional. Con internet no se descarga ningún
archivo de audio hasta que no se haga click en play, y sin internet no pasa nada.

Otros artículos en los que se incluyen audios:

- *Acordeón* (enlace a ogg, subrayado OK) [[cdpedia][3]/[wikipedia][4]]
- *Modo_mixolidio* (enlace a midi, sin subrayado #Fixme!) [[cdpedia][5]/[wikipedia][6]]
- *Escala_de_tonos_enteros* (otro reproductor incrustado) [[cdpedia][7]/[wikipedia][8]]

[1]: http://127.0.0.1:8000/wiki/Argentina
[2]: https://es.wikipedia.org//wiki/Argentina
[3]: http://127.0.0.1:8000/wiki/Acorde%C3%B3n
[4]: https://es.wikipedia.org/wiki/Acorde%C3%B3n
[5]: http://127.0.0.1:8000/wiki/Modo_mixolidio
[6]: https://es.wikipedia.org/wiki/Modo_mixolidio
[7]: http://127.0.0.1:8000/wiki/Escala_de_tonos_enteros
[8]: https://es.wikipedia.org/wiki/Escala_de_tonos_enteros

Lo que podríamos hacer con el reproductor es:

1. Reemplazarlo durante el preprocesamiento por el enlace al archivo de audio externo:
   `<a class="external" href="//upload.wikimedia.org/.../audio.ogg">reproducir audio</a>`
2. Agregar `audio {border: 1px dashed blue}` a `resources\static\css\cdpedia.css`
   para *indicar* que el reproductor solicitará un recurso externo.
3. Remover completamente del HTML toda sección que contenga un reproductor. 
4. Ocultar `<div class="mediaContainer">` con CSS.

Yo me inclino por las opciones 1 o 2, ya que no perderíamos información.

>Se sacarían solamente para las versiones de discos,
>pero para un server, se puede llegar a querer...

Para esto podríamos usar un estilo adicional para las versiones de disco que oculte
el reproductor, pero estaríamos malgastando espacio.

**Comment by facundobatista** [comment]
La opción 2 me parece la mejor; con eso dejamos lo más parecido a la página original, pero marcando que es un recurso externo que necesita internet. 

¿Cierto?

¿Te parece detallar mejor lo que se necesitaría hacer en este caso? Para no olvidarnos luego...

Gracias!

**Comment by fzuccolo** [comment]
Sí, lo mejor es dejar el reproductor como está y agregarle un borde rayado
azul, es lo menos intrusivo que se me ocurre. 

Si agregamos la regla `.mediaContainer{border: .15em dashed blue;}` al
archivo `resources/static/css/cdpedia.css`, en Firefox se muestra:

![firefox1](https://user-images.githubusercontent.com/61316398/80149570-4273f500-858d-11ea-9e6c-51e0b4a9e458.png)

![firefox2](https://user-images.githubusercontent.com/61316398/80149582-46a01280-858d-11ea-8f59-4c052dada7c4.png)

y en Chrome:

![chrome1](https://user-images.githubusercontent.com/61316398/80149712-7a7b3800-858d-11ea-926a-5620166a979a.png)

![chrome2](https://user-images.githubusercontent.com/61316398/80149699-75b68400-858d-11ea-8ac6-c1e4bcf970b4.png)

Si a nadie se le ocurre una idea más elegante, me parece bien hacerlo así.

**Comment by facundobatista** [comment]
Me parece bien.
