### ISSUE TITLE
Link a commons.wikimedia.org no se marca como externo

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#120]
_From [alecura](https://code.google.com/u/alecura/) on May 22, 2011 11:43:54_

Hay un link a http://commons.wikimedia.org/wiki/Category:Julio_Cort&#37;C3&#37;A1zar que no se marca como externo en la página de Julio Cortázar

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=119_

**Comment by fzuccolo** [comment]
Cierro este issue por ser un caso específico de #227.
