### ISSUE TITLE
problema con easy_index / coherent_hash

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#126]
_From [gringotu...@gmail.com](https://code.google.com/u/106902616802377880150/) on July 17, 2011 16:58:29_

What steps will reproduce the problem? 1. correr los tests: $ PYTHONPATH=. python tests/test_indice.py What is the expected output? What do you see instead? ======================================================================
ERROR: test_return_quantity (**main**.TestCreateEasy)
## Must return the quantity indexed.

Traceback (most recent call last):
  File "tests/test_indice.py", line 280, in test_return_quantity
    q = self.index.create(self.tempdir, [("a", 1)])
  File "/home/san/Downloads/cdpedia/trunk/src/armado/easy_index.py", line 203, in create
    cual = utiles.coherent_hash(k) &#37; N
  File "/home/san/Downloads/cdpedia/trunk/src/utiles.py", line 58, in coherent_hash
    return int(md5(txt).hexdigest()[-6:], 16)
TypeError: must be string or buffer, not int

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=125_

**Comment by NicolasSandoval** [comment]
Hola @facundobatista este issue quedo solucionado en la actualizacion que hiciste en:

- #191 Big messy branch to fix the tests.

**Comment by facundobatista** [comment]
Cierto, gracias!
