### ISSUE TITLE
Multilenguaje

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#129]
Pendientes:

- [x] poder meter portales de los distintos idiomas
- [x] copiar los textos de castellano para portugués, aymara y guaraní
- [x] que el lenguage lo tome de forma dinámica

-- --

original:

_From [facundob...@gmail.com](https://code.google.com/u/113918106348664864973/) on July 23, 2011 10:34:44_

Que se pueda generar un .iso en portugués, o alemán, o etc.

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=128_

**Comment by fzuccolo** [comment]
El idioma está harcodeado en varios lugares del código, tenemos que cambiar eso.
En `src/config.py` podríamos definir:

    LANGUAGE = None
    URL_WIKIPEDIA = None
    URL_WIKIPEDIA_TPL = 'http://{}.wikipedia.org'

y cargar el idioma al inicio de acuerdo al contexto de ejecución:

#### cdpetron
Si ejecutamos `python cdpetron.py ... <lang>`, seteamos `config.LANGUAGE = <lang>`. Este valor, al terminar de generar una CDPedia, se guarda en `temp/bloques/language.txt`  y también en el `config.py` de *cdroot*.

#### cdpedia
Si ejecutamos `python cdpedia.py` desde la raíz del proyecto (para testeo/debugging), se espera que haya una CDPedia generada en `temp`, por lo que podemos leer `<lang>` de `<DIR_BLOQUES>/language.txt`.

Si ejecutamos `python cdpedia.py` desde *cdroot* el valor de `config.LANGUAGE` ya debería estar correctamente seteado (se guarda en la generación).

Creo que con esto y algunos cambios menores más ya sería posible generar una CDPedia en otro idioma.

#### Mejora opcional

Podríamos además automatizar lo descrito en `locale/HOWTO.txt` agregando un script e.g. `locale/locale.py` que use exclusivamente el paquete `Babel` de python, algo así:

```
python locale.py <option> [value]

  -a --add-language <lang>     Create lang.po and lang/LC_MESSAGES/
  -e --extract                 Extract strings to translate
  -c --compile <lang>          Compile .mo for lang
  -s --stats                   Show percentage for each lang, etc.
```

**Comment by facundobatista** [comment]
+1 a lo de guardar el language en el config, con los cambios a `cdpetron` y `cdpedia` que dijiste después.

Además, tendríamos que dejar de pasar ese language por todos lados, y que se lo tome de la config. 

Lo de automatizar el manejo de los archivos de traducción también podría ser. Incluso que sea parte de la generación de la cdpedia... ¿de alguna manera que cdpetron se de cuenta **al principio** que la traducción está desactualizada y tire un warning? O que directamente corte el proceso?

**Comment by fzuccolo** [comment]
Sí estaría buenísimo que cdpetron verifique al inicio la traducción, que en test mode tire un warning y en modo normal corte el proceso. Voy a ver cómo se puede hacer. Es lo más lógico que cualquier funcionalidad quede expuesta a través de cdepetron.

**Comment by fzuccolo** [comment]
Cierro por que la funcionalidad base se implementó con #275, #286 y #290.
Queda pendiente #306 para un próximo release.
