### ISSUE TITLE
CDPedia Mesh

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#133]
_From [gringotu...@gmail.com](https://code.google.com/u/106902616802377880150/) on July 23, 2011 18:36:19_

Podriamos guardar los datos de forma distribuida en varias laptops en mesh de la red.

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=132_

**Comment by facundobatista** [comment]
OLPC is dead :(

Y hoy cualquier máquina tiene disco suficiente.
