### ISSUE TITLE
Asegurarse que la info de los portales quede adentro del .iso

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#135]
_From [facundob...@gmail.com](https://code.google.com/u/113918106348664864973/) on August 06, 2011 09:03:09_

No podemos tener links en el home y que el artículo no entre.

Hay que darles muchos puntos a esas páginas de "Categorías".

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=134_

**Comment by facundobatista** [comment]
Done!
