### ISSUE TITLE
Links desde los destacados deberían tener especial importancia

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#136]
_From [facundob...@gmail.com](https://code.google.com/u/113918106348664864973/) on August 13, 2011 18:45:28_

Basicamente hay que agregar un preprocesador, o modificar uno actual, que lo que haga es agarrar los "destacadso", y a las páginas apuntadas desde el mismo, darles un bonus de puntos.

Lo pongo como high porque es bastante importante para dumps chicos.

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=135_

**Comment by facundobatista** [comment]
*Need* to do this in my current "auto-portals" branch, to assure that the portals front-page is always useful.

**Comment by facundobatista** [comment]
Done!
