### ISSUE TITLE
Nombre de usuario con acentos o eñe rompe CDpedia en windows

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#142]
_From [death.pa...@gmail.com](https://code.google.com/u/101127473582441189419/) on March 05, 2012 10:05:45_

Buenas, resulta que hace un par de semanas descargué el .iso del DVD y no me funciona, aparece un aviso como si estuviera cargando, dura cierto tiempo en pantalla, abre el browser predeterminado, pero luego dice que no se pudo conectar... me gustaría saber cuál es el problema y qué debo hacer para solucionarlo... uso win 7 a 32 bit... adjunto el archivo que se crea en mi perfil de usuario...

Espero que me puedan ayudar.

Gracias!

**Attachment:** [cdpedia.log](http://code.google.com/p/cdpedia/issues/detail?id=141)

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=141_

**Comment by facundobatista** [comment]
Given the time after last response, and knowing that the problem was solved for the cases where it was checked, we can close this.
