### ISSUE TITLE
recursos estaticos faltantes ?

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#150]
_From [ccanepacc@gmail.com](https://code.google.com/u/ccanepacc@gmail.com/) on October 07, 2012 17:01:24_

El analisis de log de cdpedia cuando el minidump es recorrido por el crawler muestra unos cuantos recursos estaticos faltantes [0]

No sé como se regeneran los recursos estáticos de cdpedia, alguien podria explicar un poco ?

Notar que hay mas recursos estaticos faltantes que los que aparecen en la lista, en particular todos los .js que se cargan condicionalmente según que navegador sea detectado por javascript. (por ejemplo IEFixes.js , de issue 145 )

[0]
Missing static resources
/static/skins/css/images/add.png
/static/skins/css/images/ajax-loader.gif
/static/skins/css/images/arrow-down-icon.png?1
/static/skins/css/images/audio-icon.png?2
/static/skins/css/images/document-icon.png?2
/static/skins/css/images/feed-icon.png
/static/skins/css/images/file-icon.png?2
/static/skins/css/images/lock-icon.png?2
/static/skins/css/images/mail-icon.png?2
/static/skins/css/images/news-icon.png?2
/static/skins/css/images/page-fade.png?1
/static/skins/css/images/portal-break.png?1
/static/skins/css/images/preferences-base.png?1
/static/skins/css/images/preferences-break.png?1
/static/skins/css/images/preferences-fade.png?1
/static/skins/css/images/remove.png
/static/skins/css/images/search-fade.png?1
/static/skins/css/images/spinner.gif
/static/skins/css/images/tab-break.png?1
/static/skins/css/images/tab-current-fade.png?1
/static/skins/css/images/tab-normal-fade.png?1
/static/skins/css/images/talk-icon.png?2
/static/skins/css/images/ui-bg_flat_0_000000_40x100.png
/static/skins/css/images/ui-bg_flat_100_ffffff_40x100.png
/static/skins/css/images/ui-bg_highlight-hard_100_e2eef6_1x100.png
/static/skins/css/images/ui-bg_highlight-hard_100_ffffff_1x100.png
/static/skins/css/images/ui-bg_highlight-hard_55_fbf9ee_1x100.png
/static/skins/css/images/ui-bg_inset-soft_95_fef1ec_1x100.png
/static/skins/css/images/ui-icons_000000_256x240.png
/static/skins/css/images/ui-icons_2e83ff_256x240.png
/static/skins/css/images/ui-icons_333333_256x240.png
/static/skins/css/images/ui-icons_cd0a0a_256x240.png
/static/skins/css/images/user-icon.png?1
/static/skins/css/images/video-icon.png?2
/static/skins/css/images/watch-icon-loading.gif?1
/static/skins/css/images/watch-icons.png?1
/static/skins/images/vector/collapsibleNav/arrow-down.png?1
/static/skins/images/vector/collapsibleNav/arrow-left.png?1
/static/skins/images/vector/collapsibleNav/arrow-right.png?1
/static/skins/images/vector/collapsibleNav/portal-break.png?1
/static/skins/images/wikiEditor/dialogs/button_disabled.png?1
/static/skins/images/wikiEditor/dialogs/button_down.png?1
/static/skins/images/wikiEditor/dialogs/button_off.png?1
/static/skins/images/wikiEditor/dialogs/button_over.png?1
/static/skins/images/wikiEditor/dialogs/close_x.png?1
/static/skins/images/wikiEditor/dialogs/insert-link-exists.png?1
/static/skins/images/wikiEditor/dialogs/insert-link-external-rtl.png?1
/static/skins/images/wikiEditor/dialogs/insert-link-external.png?1
/static/skins/images/wikiEditor/dialogs/insert-link-invalid.png?1
/static/skins/images/wikiEditor/dialogs/insert-link-notexists.png?1
/static/skins/images/wikiEditor/dialogs/titlebar_fade.png?1
/static/skins/images/wikiEditor/toolbar/arrow-down.png?1
/static/skins/images/wikiEditor/toolbar/arrow-left.png?1
/static/skins/images/wikiEditor/toolbar/arrow-right.png?1
/static/skins/images/wikiEditor/toolbar/base.png?1
/static/skins/images/wikiEditor/toolbar/button-sprite.png?1
/static/skins/images/wikiEditor/toolbar/loading-small.gif?1
/static/skins/images/wikiEditor/toolbar/loading.gif
/static/skins/images/wikiEditor/toolbar/loading.gif?2

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=149_

**Comment by fzuccolo** [comment]
A muchas de estas imágenes las agregan los CSS de skins, por ej:

https://github.com/PyAr/CDPedia/blob/aae19a8bf2a3cbf626057fd4657679ab61bd0019/resources/static/skins/css/main.css#L209

Algunas creo que se usan en el cuadro de edición del artículo (no nos interesan) pero las otras no sé. No se descargan por que no figuran en el HTML, puede ser que el crawler busque en los CSS también?

Se podrían descargar y apuntar las URL a `/static/skins/css/images/`. Serán unos [30+ PNGs][1], no más de 200KB en disco. Si no vemos cuáles serían importantes y dejamos sólo algunas.

[1]: https://wiki.creativecommons.org/skins/Vector/images/

**Comment by facundobatista** [comment]
Algunas cosas se fixearon en su momento, otras (algunas de CSS, por ejemplo) ahorita.

Vale la pena revisar qué de todo lo marcado acá sigue estando "vivo", o nos quedamos con #231 que nos va a mostrar lo que falte y ya?

**Comment by fzuccolo** [comment]
Sí, me parece mejor quedarnos con #231 y arreglar después lo que salte con el crawler.
