### ISSUE TITLE
404 para 'minus.png' , un recurso de tutorial ?

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#152]
_From [ccanepacc@gmail.com](https://code.google.com/u/ccanepacc@gmail.com/) on October 07, 2012 18:33:47_

En cdpedia.log
127.0.0.1 - - [03/Oct/2012 14:43:27] "GET /cmp/tutorial/minus.png HTTP/1.1" 404 -

Mirando el log del crawler:

"NOT FOUND" (404) at link localhost:8000/cmp/tutorial/minus.png (from localhost:8000/cmp/tutorial/_static/doctools.js)

No sé a que pagina de cdpedia corresponderia.

Pareceria que el recurso está pero que la ubicación o el link están mal.
Tenemos en 
cdpedia/assets
el file
tutorial.tar.bz2
que tiene entre otras cosas el subtree
tutorial/
    _static/
        doctools.js
        minus.png

Pareceria entonces que hay que cambiar el link dentro del .js o mover minus.png un nivel hacia arriba (vean los url de los dos recursos)

No hice pruebas de la solucion propuesta porque no le tengo confianza al tar.bz2 que pueda obtener en windows; las diferentes aplicaciones de compresion (winzip, winrar, 7-zip,...) pueden producir diferentes resultados descomprimiendo ciertos tar.*

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=151_

**Comment by facundobatista** [comment]
Vamos a actualizar el tuto entero.
