### ISSUE TITLE
ignorable 404 para /w/index.php ?

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#153]
_From [ccanepacc@gmail.com](https://code.google.com/u/ccanepacc@gmail.com/) on October 07, 2012 19:15:08_

Evidentemente cdpedia no usa un interprete .php , pero el cdpedia.log saca:

127.0.0.1 - - [03/Oct/2012 16:46:10] "GET /w/index.php HTTP/1.1" 404 -

y la entrada correspondiente del crawler

14:35:41 Error:  "NOT FOUND" (404) at link localhost:8000/w/index.php (from localhost:8000/static/skins/js/header.js)

Se puede ignorar esto o seria necesario algun ajuste en header.js ?

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=152_

**Comment by facundobatista** [comment]
Es probable que esto no siga pasando (porque cambió mucho todo); de última si tenemos un problema similar, lo vamos a encontrar con el crawler.
