### ISSUE TITLE
404 for some /static/skins/js/wikibits.js resources

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#154]
_From [ccanepacc@gmail.com](https://code.google.com/u/ccanepacc@gmail.com/) on October 07, 2012 19:51:37_

En log del crawler
14:35:41 Error:  "NOT FOUND" (404) at link localhost:8000/sort_up.gif (from localhost:8000/static/skins/js/wikibits.js)
14:35:41 Error:  "NOT FOUND" (404) at link localhost:8000/sort_down.gif (from localhost:8000/static/skins/js/wikibits.js)
14:35:41 Error:  "NOT FOUND" (404) at link localhost:8000/sort_none.gif (from localhost:8000/static/skins/js/wikibits.js)

Veo files con esos nombres en
cdpedia/assets/static/skins/css/images

aunque no sé si el .js quiere indicar esos files.

El .js construye dinámicamente el path, y pareciera que se esta equivocando o algo lo confunde.

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=153_

**Comment by facundobatista** [comment]
Es probable que esto no siga pasando (porque cambió mucho todo); de última si tenemos un problema similar, lo vamos a encontrar con el crawler.
