### ISSUE TITLE
falso positivo (posiblemente) de AVG con pyinstaller

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#155]
_From [ccanepacc@gmail.com](https://code.google.com/u/ccanepacc@gmail.com/) on October 11, 2012 16:49:33_

Hoy AVG marco como infectado el cdpedia.exe construido hace algunos dias, y que se usó sin advertencias varias veces.

Llené un reporte de falso positivo para AVG.

Comprobe que un run.exe que trae pyinstaller y posiblemente use al construir cdpedia.exe saca el mismo diagnostico.

Busque en la lista de pyinstaller y hay reporte similar [0], sin resolucion.

Una busqueda rapida en el issue tracker de pyinstaller no muestra nada. 

Posteé en la lista de pyinstaller, no puedo linkear porque espera aprobacion para aparecer en publico.

En el thread citado se comenta que py2exe solucionó problemas de falsos positivos.

[0] https://groups.google.com/forum/#!topic/pyinstaller/Y-PsWjys6GA

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=154_

**Comment by facundobatista** [comment]
Given the time passed since this issue was posted, and that AVG and pyinstaller evolved to fix the problem, we can close this.
