### ISSUE TITLE
Agregar aviso de actualización disponible

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#156]
_From [miguel.g...@gmail.com](https://code.google.com/u/104469511452121882509/) on October 24, 2012 13:54:29_

Estamos trabajando para incorporar la cdpedia a Huayra GNU/Linux, nosotros la instalamos a disco y la idea es:
 Agregar un link en la pagina principal de la CDPedia cuando hay un nuevo pack de datos disponible.
  La url para chequear si hay nuevas versiones sería configurable.Algo como http://www.example.org/cdpedia_update.txt Y que ese txt tenga el nro de version del ultimo pack de datos y una url para descargar ese pack.

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=155_

**Comment by facundobatista** [comment]
Más allá que se implemente un .deb para esto o no, el "tener un script que revise si hay actualizaciones" no tendría sentido según dice arriba.
