### ISSUE TITLE
traduje la página web de English y Húngaro

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#158]
_From [m4g...@gmail.com](https://code.google.com/u/116886680541145230052/) on November 30, 2012 11:33:50_

Attached

**Attachment:** [english magyar](http://code.google.com/p/cdpedia/issues/detail?id=157)

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=157_

**Comment by facundobatista** [comment]
Deberíamos migrar estos textos a templates, como indica #178.

**Comment by macorv** [comment]
Hola @facundobatista, ya que vamos a hacer este trabajo tiene sentido agregar portugués?

**Comment by facundobatista** [comment]
Una vez que tenemos el template, la gente que sepa el idioma XYZ puede agregarlo sin drama. Pero no es responsabilidad "nuestra" (si sabés portugués y querés escribirlo, adelante!).

**Comment by NicolasSandoval** [comment]
Me parace que los archivos ya no estan disponibles.

**Comment by facundobatista** [comment]
Ahora tenemos templates en castellano e inglés en `web/templates/`, si alguien quiere proponer otros idiomas, tienen que proveer templates de ese estilo... Cierro esto, entonces
