### ISSUE TITLE
Agregar ayuda para windows en el discourse y linkearlo

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#161]
_From [ccanepacc@gmail.com](https://code.google.com/u/ccanepacc@gmail.com/) on August 21, 2013 11:22:51_

Si tenés problemas con cdpedia en windows agregá a éste issue o creá una nueva, tratando de poner la siguiente información:

Version de windows (xp , win7 32bits, etc)

Que archivo de cdpedia bajaste, por ejemplo cdpedia-0.8-cd.iso, cdpedia-0.8-dvd5.iso

Antes de darle al cdpedia.exe que es lo que hacés ? Montar el iso con daemon tools, quemarlo a CD / DVD, montar el iso con daemon tools y copiar todos los contenidos a un directorio 'mi_cdpedia' del disco rigido, ...

Muy bien, ahora ya tenemos visible en alguna parte a cdpedia.exe, haciendole doble click deberia pasar esto:

```
En Administrador de Tareas de windows, en la solapa 'procesos' deberia ser visible un cdpedia.exe (esta es la parte que va a servirle paginas al navegador). Entonces, lo ves ?

Si no tenias abierto el navegador por defecto de tu maqina (Internet Explorer, Firefox,...) deberia arrancarse solo y mostrar la pagina de entrada para la cdpedia. (puede tardar algunos segundos). Por otro lado, si el navegador por defecto estaba abierto deberia aparecer una nueva pestaña mostrando la página de entrada de cdpedia. A veces uno no se dá cuenta que apareció una nueva pestaña. Entonces, cuál es tu navegador, y, apreció la portada en alguna pestaña ?

En algunas circunstancias que no son claras ocurre que el servidor de páginas arranca pero no se abre el navegador. Si ves cdpedia.exe entre los procesos del administrador de tareas, podés probar a lanzar manualmente el navegador:
arrancar el navegador de tu preferencia
en la barra de direcciones poner 'http://localhost:8000' (sin las comillas) y dar enter
Esto le dice al navegador que conecte a tu propia maquina en el puerto 8000, que es donde cdpedia.exe está esperando para servir páginas, y deberias ver en el navegador la portada de cdpedia; a partir de alli se navega normalmente. Entonces, esto sirvió en tu caso?

A lo largo de las pruebas mencionadas aparecio algun cartel de error o advertencia ? Si sí, que es lo que decian ?

cdpedia.exe guarda informacion de la sesion (incluyendo mensajes de error) en un archivo cdpedia.log que se guarda en 
    windows xp: C:\Documents and Settings\<tu usuario>
    window vista y 7: c:\usuarios\<tu usuario>
Aparece este archivo en tu maquina al correr cdpedia.exe ?
Cuales son sus contenidos ? (si es muy largo ponerlo como attachment)

Si el proceso cdpedia.exe es visible en Administrador de tareas pero la conexion manual mencionada antes no funciona, podria haber un problema con el firewall.
En este caso habria que habilitar cdpedia.exe en el firewall. Esto depende de qué firewall se esté usando.
Si es el firewall que ya trae windows hay que ir a 'inicio' -> 'configuracion' -> 'panel de control' -> 'firewall de windows', click en la solapa excepciones, click en el boton 'agregar programas', navegar hasta donde este el cdpedia.exe y dar click en aceptar.

Algo a tener en cuenta: si se arranca cdpedia.exe pero no se navega por las paginas de cdpedia, (por ejemplo salimos a comprar algo), entonces el servidor de paginas se apaga solo (cdpedia.exe deja de estar visible entre los procesos de Administrador de Tareas
```

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=161_

**Comment by facundobatista** [comment]
We should move this info to the web page

**Comment by facundobatista** [comment]
Mover este texto a la web, sí, pero tocar el texto diciendo que siempre abrir un issue nuevo (no agregar a este).

**Comment by NicolasSandoval** [comment]
Cuando decís mover a la web, te referis poner el texto en http://cdpedia.python.org.ar/.

**Comment by facundobatista** [comment]
> Cuando decís mover a la web, te referis a poner el texto en http://cdpedia.python.org.ar/.

Exacto. Lo que sería en realidad *hoy* tocar `web/index.html` (en un futuro cercano vamos a tener templates, habria que tocar eso).

**Comment by facundobatista** [comment]
Ya tenemos templates! Hay que incorporar esto!

**Comment by facundobatista** [comment]
# NO HAY QUE PONERLO EN EL TEMPLATE

- [ ] Meter esto como pregunta y respuesta en [el discourse](https://pyar.discourse.group/c/cdpedia/5)
- [ ] Y meter la URL general del discourse en el template

**Comment by Berelarsenp** [comment]
La URL del Discourse ya está en el template acá
![image](https://user-images.githubusercontent.com/22670036/87853790-99b30880-c8e3-11ea-9208-af09c0c9f3a1.png)

Por ahí se puede cambiar el texto a `Unite al foro para charlar o reportar un problema >>` o agregar otro botón al final de `¿Necesitás ayuda? Preguntá en Discord`

**Comment by facundobatista** [comment]
Sí, quizas lo mejor es al final, luego de explicar que hay que descargar y cómo usar, un "Si necesitás ayuda..." con el link al discourse...

**Comment by Berelarsenp** [comment]
FAQ y ayuda agregada al discourse en forma de tema https://pyar.discourse.group/t/tenes-problemas-con-cdpedia-en-windows/363
