### ISSUE TITLE
Mejorar el uso de utilities/scraper.py desde cdpetron

### ISSUE THREAD

**Issue by facundobatista** [PyAr/CDPedia#166]
Dos aspectos muy necesarios:
- Importarlo, no ejecutarlo externamente (ojo con esto, hay que jugar con el reactor de twisted)
- Dejar de hacer prints, integrarlo a logging, y usar el TimingLogger

**Comment by facundobatista** [comment]
Twisted se va a ir de acá, deberíamos usar asyncio, igual no es trivial tener sólo eso asincrónico.

**Comment by macorv** [comment]
@facundobatista para la parte del logging de esta tarea, me pregunto si es la única parte donde se imprimen mensajes en pantalla (en lugar de loggear). Y, si en todo caso, vale la pena abrir un issue nuevo para revisar y corregir todos los scripts.

**Comment by facundobatista** [comment]
Te diría de abrir nuevos issues cuando nos vayamos cruzando con el "problema". No armar una tarea de "revisar eso"...

**Comment by laureanoSilva** [comment]
Voy a tratar de entender si podemos usar esto: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

Que funciona en Py2 gracias a esto: https://pypi.org/project/futures/

**Comment by facundobatista** [comment]
Ya está!
