### ISSUE TITLE
Revision headers in all the pages

### ISSUE THREAD

**Issue by facundobatista** [PyAr/CDPedia#167]
Here is what I see in top of all pages:

```
(dif) ← Revisión anterior · Ver revisión actual (dif) · Revisión siguiente → (dif)
```

That shouldn't be there.

**Comment by laureanoSilva** [comment]
Hola, yo no veo eso. podria chequearlo alguien mas? puede ser que se haya "arreglado" desde 2015?

**Comment by facundobatista** [comment]
Totalmente, seguro puede haberse arreglado porque soportamos sacarlo en alguna de las tantas limpiezas que hacemos...

**Comment by facundobatista** [comment]
Confirmado que no se ve... uno menos!
