### ISSUE TITLE
Non included images are broken

### ISSUE THREAD

**Issue by facundobatista** [PyAr/CDPedia#168]
It seems in the HTML it's pointing  to the image itself, which is not included, instead of doing the javascript thingie

**Comment by facundobatista** [comment]
See, for example: http://127.0.0.1:8000/wiki/Juego_de_mesa

**Comment by spiccinini** [comment]
Por ejemplo en la pagina `wiki/$` se ve ahi
![image](https://user-images.githubusercontent.com/500841/80168776-220e5f80-85ba-11ea-9a48-b70f384d06a2.png)

pero deberia verse así:

![image](https://user-images.githubusercontent.com/500841/80168877-6a2d8200-85ba-11ea-88bd-332f01154b59.png)
