### ISSUE TITLE
Falla al abrir el navegador web

### ISSUE THREAD

**Issue by humitos** [PyAr/CDPedia#170]
No tengo CDPedia instalado para pegarles el traceback acá, pero la cuestión es que si no tenés definido un browser por default en tu sistema operativo `webbrowser.open` explota.

Me pasó con https://github.com/edvm/pysenteishon/

```
Traceback (most recent call last):
  File "src/web.py", line 95, in <module>
    webbrowser.open(url)
  File "/usr/lib/python3.4/webbrowser.py", line 60, in open
    if browser.open(url, new, autoraise):
  File "/usr/lib/python3.4/webbrowser.py", line 238, in open
    success = self._invoke(args, True, autoraise)
  File "/usr/lib/python3.4/webbrowser.py", line 203, in _invoke
    stderr=inout, start_new_session=True)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

Deberíamos manejar eso.

**Comment by facundobatista** [comment]
No sólo deberíamos capturar este error, sino que tambien deberíamos tirar un mensaje al usuario, onda "Por favor abrí la siguiente página..."

**Comment by NicolasSandoval** [comment]
Después de varios intentos sin navegadores webbrowser.open no explota.
Cuando no encuentra navegadores abre directamente cualquier editor de texto existente o cualquier lugar donde pueda colocar el html.
Puede ser que lo hayan corregido en las nuevas versiones.

**Comment by facundobatista** [comment]
Incluso probé `webbrowser.open` en el docker de un debian muy pelado, tanto en 2.7 como en py3, y no explota (pero contesta `False`, porque no pudo)

**Comment by facundobatista** [comment]
Nos queda entonces darle un mensaje al usuario... entonces, si `False`, decirle algo como "You need a browser installed in your system to access the CDPedia content."

**Comment by NicolasSandoval** [comment]
Claro pero si esperamos el `false` de webbrowser tendria que estar el sistema pelado pero si llega a tener un editor de texto donde colocarlo?
El docker no tiene ni editores de texto?
Por que si abre desde un editor y muestra el html plano por ahi el usuario va a pensar que anda mal CDPedia.

**Comment by facundobatista** [comment]
No podemos hacer mucho en ese caso... O sea, si tiramos abrir el browser, y efectivamente parece que lo abre... no tenemos donde agarrarnos si el sistema nos miente.

**Comment by NicolasSandoval** [comment]
Estoy de acuerdo  intente por varios lados y la verdad que sin meterme en el trabajo de `webbrowser` es medio complicado y repetir el codigo ajustado no seria lo ideal.

Habia encontrado una solución simple obteniendo la lista en la que `webbrowser` guarda los registros de lo que encuentra en el sistema. Pero en la versión de `python3.7` la colocaron en `threading.Rlock` y ya no se podría utilizar para sacar los files que se encargan de buscar en el sitema opciones si `webbrowser` no encuentra navegadores determinados. En mi caso `xdg-open`. 

Ejemplo de hacer parte del trabajo de webbrowser y solo chequear los navegadores que busca antes de pasar a los handlers del sistema.
 https://linkode.org/#P1Y1PCGENXbmX6RG46C5P6

Ejemplo utilizando la lista de webbrowser
https://linkode.org/#OqZ54s4OfyD6cftM73OtK5

Creo igualmente que el problema central esta en `xdg-open`.

**Comment by facundobatista** [comment]
Te complicaste la vida.

Lo único que tenías que hacer es llamar a `webbrowser.open(url)` y el resultado de esa función es la que te dice si pudo abrir la página o no.

Algo como:

    opened_ok = webbrowser.open(url)
    if not opened_ok:
        ...
