### ISSUE TITLE
En mil docstrings/comments todavía se menciona launchpad, actualizar links a GH

### ISSUE THREAD

**Issue by facundobatista** [PyAr/CDPedia#187]

**Comment by Berelarsenp** [comment]
@facundobatista: 
1. ¿qué hacemos con el [link de cdpedistas](https://github.com/PyAr/CDPedia/blob/master/web/index.html#L186) que aparece al final de la landing?
2. Hay un montón de links de launchpad que son de otros proyectos (como beautiful soup o lxml, x ej.) y particularmente a algunos bugs.. entiendo que a esos no hay que tocarlos, ¿verdad?

**Comment by tenuki** [comment]
Me meto:

>     1. ¿qué hacemos con el [link de cdpedistas](https://github.com/PyAr/CDPedia/blob/master/web/index.html#L186) que aparece al final de la landing?

Creo que hacer una pagina especial para los cdpedistas no tiene mucho sentido ahora.. yo cambiaria el link por este: https://raw.githubusercontent.com/PyAr/CDPedia/master/AUTHORS.txt 
o sino este: https://github.com/PyAr/CDPedia/graphs/contributors . 

Pero el primero me parece que esta bueno porque es mas controlable.


>     2. Hay un montón de links de launchpad que son de otros proyectos (como beautiful soup o lxml, x ej.) y particularmente a algunos bugs.. entiendo que a esos no hay que tocarlos, ¿verdad?

Si algo apunta a un repo o issue system de 3eros no lo cambiaria (si queremos ademas podriamos ver si siguen sirviendo los links.. y si no funcionan veria que hacer).

Creo que lo que se pretende es actualizar los links "de cdpedia" principalmente a lugares actuales.

**Comment by facundobatista** [comment]
+1 a todo, y el PR está casi para landear, así que esto esta listo...
