### ISSUE TITLE
Eliminar código de terceros, o apropiarlo

### ISSUE THREAD

**Issue by facundobatista** [PyAr/CDPedia#193]
Hay código de terceros commiteado... creo que en dos grupos:

- `bmp.py`: esto parece que lo trajimos de algún lado para usarlo... ¿no hay algo a nivel "lib" que se pueda utilizar? si no, apropiémoslo definitivamente

- todo lo que está en `src/third_party/`: esto creo que es porque lo tenemos que meter en el iso/tarball para que funcione "el server"... acá lo ideal sería hacer algo de otra manera, frizando de alguna manera las libs actuales... tengo algo en mente para esto, habría que probarlo...

**Comment by NicolasSandoval** [comment]
Estaria para cerrar con el #248 o falta ver lo de bmp?

**Comment by fzuccolo** [comment]
Una alternativa para eliminar el `bmp.py` sería hacer una función que genere una imágen SVG con el width/height que necesitemos, por ej.:

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="80">
    <rect x="0" y="0" width="100" height="80" style="fill:#eeeeee"/>
    <rect x="0" y="0" width="100" height="80" style="fill:none;stroke:#aaa;stroke-width:4"/>
    <line x1="0%" y1="0%" x2="100%" y2="100%" style="stroke:#aaa;stroke-width:2"/>
    <text x="50%" y="50%" text-anchor="middle" style="fill:#aaa">
        Sin imágen
    </text>
</svg>
```
se mostraría así:

![Screenshot_2020-06-16 Screenshot](https://user-images.githubusercontent.com/61316398/84813847-f1114080-afe6-11ea-8e13-8743ad83f5d2.png)

Y en `web_app` hacemos:

```python
img = render_svg(width, height)
return Response(img, mimetype='image/svg+xml')
```

**Comment by spiccinini** [comment]
Originalmente la idea era no usar SVG porque no estaba soportado en browsers viejos, que son los que en general usarían o usaban quienes usa la CDPedia.
Quizás podemos revisar eso?

**Comment by facundobatista** [comment]
Creo que la clave es asegurarnos que esté soportado hace "mucho" (entre comillas, porque tenemos que definir cuanto es mucho) en todos los browsers (especialmente IE!!).

Si estamos confiados con eso, me parece la mejor solución.

**Comment by fzuccolo** [comment]
IE soporta SVG nativamente a partir de la versión 9 (Win7, 2011), se ve así:

<img src="https://user-images.githubusercontent.com/61316398/85323585-9e300100-b49e-11ea-89ad-b55cbb696d9a.png" width="500">

Para versiones anteriores que no soportan SVG se puede usar un *workaround*: remover el atributo `alt` de los tag `<img>` y agregarles `width` y `height`. En IE6 (WinXP, 2008) se vería así:

<img width="500" alt="ie6" src="https://user-images.githubusercontent.com/61316398/85324101-9b81db80-b49f-11ea-82f7-de4ac0e6bb66.png">


Este workaround vale para otros navegadores, por ej. Firefox sin SVG:

<img width="500" src="https://user-images.githubusercontent.com/61316398/85324463-4397a480-b4a0-11ea-851b-8bc3e1da6d7e.png">


**Tener en cuenta**: la mayoría de las fórmulas que estamos descargando son SVG, 
y en navegadores antiguos se mostrará siempre el código latex, tanto con `bmp.py`
como con el workaround anterior. No sé si hay manera de pedir fórmulas en PNG.
