### ISSUE TITLE
cambiar el boton de "artículo al azar"

### ISSUE THREAD

**Issue by laureanoSilva** [PyAr/CDPedia#201]
En la wikipedia esa funcionalidad existe, pero como un link "normal". Me parece que de esa forma estaríamos mas cerca del estilo visual de la wiki online. 

Sería pasar de esto: 
![art-al-azar-actual](https://user-images.githubusercontent.com/15295559/80248944-50864c00-8647-11ea-9816-41766cb8757f.png)     

A esto:
![art-al-azar](https://user-images.githubusercontent.com/15295559/80248939-4f551f00-8647-11ea-9d35-85fbfc96c5ae.png)

**Comment by NicolasSandoval** [comment]
Me parece que la idea principal era darle protagonismo al random y al colocarla ahí se perdería un poco, me gustaría por ahí cambiarle la vista.

**Comment by laureanoSilva** [comment]
También pensé en un principio que se quiso destacar la función poniendo el botón. Pero pensando en que la wiki original tiene esa función y la muestra como un link más,  me pareció que estaría bueno respetar ese "estilo".

**Comment by facundobatista** [comment]
Eso se había puesto como botón en la época que no teníamos portada. El artículo al azar era una de las formas de "arrancar explorando", más allá de la búsqueda en sí.

Hoy tenemos un portal, la gente puede hacer click en mil lugares interesantes. Tener un artículo al azar no es tan importante.

+1 a ponerlo como link sólo.
