### ISSUE TITLE
'Broken pipe' al iniciar CDPedia (en Firefox?)

### ISSUE THREAD

**Issue by Berelarsenp** [PyAr/CDPedia#207]
#### Problema
Al levantar `cdpedia.py` veo por consola el siguiente error
```
Exception happened during processing of request from ('127.0.0.1', 44172)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```
#### Entorno:
* **SO:** Ubuntu 18.04.4 LTS
* **Navegador default:** Firefox 75.0

#### Casos:
1. Ejecuté `./cdpedia.py` en consola y levantó en firefox tirando el error indicado. Probé:

    * terminar la sesión sin cerrar la pesaña de cdpedia en el navegador y volver a levantar varias veces una no me arrojó el error pero el resto sí.
    * Lo mismo que el caso anterior pero cerrando la pestaña y también arrojó el error.

2. Cambié el navegador default por Chrome y probé los mismos casos que antes y en **ninguno** vi el error en consola

3. Volví a setear Firefox por defecto y las siguientes pruebas que hice no arrojaron el error

**Comment by fzuccolo** [comment]
Actualicé werkzeug a la versión 1.0.1 en este [branch][1] y el Broken pipe ya no se produce, al menos yo no pude reproducirlo.

[1]: https://github.com/PyAr/CDPedia/compare/update-werkzeug

**Comment by facundobatista** [comment]
Es *muy* probable que se haya solucionado, entonces... cerremos esto, total de última si vuelve a aparecer lo volvemos a abrir :)
