### ISSUE TITLE
Remover convertidor.py

### ISSUE THREAD

**Issue by fzuccolo** [PyAr/CDPedia#212]
El módulo [`src/preproceso/convertidor.py`][1] no es utilizado por ningún otro módulo, lo verifiqué borrando el archivo, generando una CDPedia y corriendo los tests. ¿Deberíamos removerlo?

[1]: https://github.com/PyAr/CDPedia/blob/master/src/preproceso/convertidor.py

**Comment by facundobatista** [comment]
Lo borré.
