### ISSUE TITLE
Regenerar cdpedia.exe

### ISSUE THREAD

**Issue by fzuccolo** [PyAr/CDPedia#222]
Luego de #218 el `cdpedia.exe` del autorun de Windows dejó de funcionar. Hay que regenerarlo utilizando una versión actual de pyinstaller. No es prioritario hacerlo ahora, ya que cdpedia funciona bien corriendo `python cdpedia.py`. Mejor esperemos a estar en Py3 para encarar esto.

**Comment by facundobatista** [comment]
Cerramos este en favor de #289 , que es el nuevo plan.
