### ISSUE TITLE
Arreglar link a wikipedia en footer

### ISSUE THREAD

**Issue by NicolasSandoval** [PyAr/CDPedia#225]
> sitio online de Wikipedia

**Comment by fzuccolo** [comment]
En los artículos el enlace del footer es correcto. El error está en los footer de Portada y páginas institucionales (Ayuda, Términos de uso, Licencia, etc.).

**Comment by NicolasSandoval** [comment]
@fzuccolo si me refiero al de portada este lo viste vos, es el unico que no direcciona al lugar correcto, los avisos como Aviso legal o Acerca de wikimedia devuelven que no pudieron ser incorporados, esto no se si es asi por la construcción en test mode o es random la incorporacion.

**Comment by NicolasSandoval** [comment]
Cuando se accede a una pagina del servidor se actualiza la url a wikipedia y el enlace funciona correctamente.
