### ISSUE TITLE
Crear crawler para analizar links

### ISSUE THREAD

**Issue by NicolasSandoval** [PyAr/CDPedia#231]
- La idea es implementar un crawler que analice los links en tiempo de ejecución de la pagina web.

**Comment by dmascialino** [comment]
buenas! puedo ponerme a laburar en este issue

**Comment by fzuccolo** [comment]
Con los cambios de #313 el *url_tracker* dejó de encontrar algunas páginas. Un fix posible es cambiar

https://github.com/PyAr/CDPedia/blob/271e8dd3a9a74957b09d1f4c4b5eadce9084c3e5/utilities/tests/url_tracker.py#L80

por `url_quote = parse.quote(parse.unquote(url), safe='/:')`.

La razón de esto es que en `pag_elegidas.txt` se guarda el nombre de disco del artículo (con chars especiales quoteados). Por ej. para el título `$9.99` el nombre de disco es `$9%2E99`. Entonces para recuperar el nombre original primero tenemos que desquotear el punto `$9.99` para luego obtener el link correcto `%249.99` (sin ese paso nos quedaría `%249%252E99`).

**Comment by NicolasSandoval** [comment]
Genial @fzuccolo , gracias muy bueno el seguimiento.
Corregido en:
#336

**Comment by facundobatista** [comment]
```
$ python3 utilities/tests/url_tracker.py
Pages in this CDPedia version 8000
Testing pages in CDPedia 8000 ·:|:· In Parallel Universe 0
Congrats!! All pages are included in CDPedia
```
