### ISSUE TITLE
Capturar traceback si no hay conexion

### ISSUE THREAD

**Issue by NicolasSandoval** [PyAr/CDPedia#266]

**Comment by facundobatista** [comment]
Este issue necesita una mejor descripción y contenido. Capturar el traceback dónde? Para qué? Qué significa que no hay "conexión"? (por ejemplo, si tenés conexión pero no DNSs, debes capturar o no? etc...)

Gracias!

**Comment by NicolasSandoval** [comment]
La idea es capturar este tracebak.

https://linkode.org/#fmk5YK2KhdD0lXvPwyPJ97

Y devolver algo como esto:

```2020-07-02 19:31:45,334  cdpetron             ERROR    Check if you have internet connection [Errno -2] Name or service not known```

Se prodria hacer algo mas generico que abarquen varios errores.

**Comment by NicolasSandoval** [comment]
Cierro este issue por no ser de importancia para la release 0.9
