### ISSUE TITLE
Use LZMA or Zstandard compression for blocks

### ISSUE THREAD

**Issue by spiccinini** [PyAr/CDPedia#270]
Zstandard es un algoritmo de compresión moderno que es MUY rapido para descomprimir y además comprime casi tan bien como LZMA (xz). Pasar a usar Zstandard entonces nos daría una compresión teórica mucho mejor que bz2 y además también mayor velocidad. Sería importante hacer la comparación.

Documentación y benchmarks se pueden encontrar en la pagina del proyecto: https://facebook.github.io/zstd/
Bindings para python https://pypi.org/project/zstandard/ (hay wheels disponibles, habría que ver que tal con pyinstaller para windows).

**Comment by facundobatista** [comment]
El problema es cómo metés los binarios para todas las plataformas. Porque si no te lo garantiza la stdlib, tenés que hacerte cargo vos.

O sea, usamos `bzip2`, eso implica que si la persona tiene Python en, ponele, la Mac, va a poder abrir ese bz2.

Pero si no está en la stdlib, vos tenés que garantizar que el compilado específico esté adentro de la CDPedia. 

La pregunta entonces es: ¿cuanto pesa meter todos los wheels de todas las plataformas? ¿cómo te asegurás que estás cubriendo todo?

**Comment by spiccinini** [comment]
Tenia en la cabeza de tal vez investigar de tener un dll, y shared objects para linux y mac compilados estaticos (para no depender de nada)... y usar eso desde el modo CFFI que tiene el paquete de python de zstandard (que hay que ver si realmente anda para esto o no).... quizas hay demasiados dragones inclusive en el camino feliz.
Tal vez podemos probar XZ (que si esta en la stdlib en python3) y ver la diferencia con bz2 (deberia ser no despreciable)

**Comment by facundobatista** [comment]
+100 a ir a XZ que está en la stdlib!!

**Comment by spiccinini** [comment]
Hice una prueba con 15000 articulos (5 bloques). 
```
>>> for bz2, xz in zip([1510445, 1466849, 1383730, 1469716, 1826866], [1202452, 1170480, 1096968, 1180692, 1448972]):
...     print((1 - xz / bz2) * 100)
... 
20.39087818490577
20.204465490312906
20.723840633649626
19.665295880292522
20.685370465047793
```

Nos estariamos ahorrando 20% de espacio usando XZ en los bloques de articulos. Esto fue usando la configuración por defecto de lzma (que usa `6`).

Tiempos de decompresión de uno de estos bloques de prueba:
bz2 decompression time: 1.266561s
xz decompression time: 0.170054s

O sea que xz es ~7.5 veces mas rapido para descomprimir (en mi disco SSD y el file probablemente cacheado en ram).
