### ISSUE TITLE
Use sqlite to a better index 

### ISSUE THREAD

**Issue by marian-vignau** [PyAr/CDPedia#271]
Todavía estoy en medio de la confección, recién indiza y hace el search, pero acá está una pre-alfa (porque todavía no busca por palabra parcial, ni una página random... pero algo ya está para ser visto
https://github.com/PyAr/CDPedia/tree/sqliteidx

**Comment by facundobatista** [comment]
Poder ir a un backend del índice como SQLite sería genial, porque es algo bastante optimizado, y aunque tiene sus limitaciones, las mismas no nos afectan (como ser monousuario). 

Algunas cosas a tener en cuenta... si se nos ocurren más vayamos anotando así estamos seguros que revisamos todo (no todas son cosas para "arreglar", hay otras para confirmar lo bueno del cambio):

- [ ] poner este índice en el test case que prueba toda la API (pero tener en cuenta que podemos cambiar la API si queremos optimizar algo)
- [ ] poder armar ok el .exe de Windows (al venir SQLite en la stdlib, estamos cubiertos en los linuxes y macs, pero no sé cómo va a ser en windows)
- [ ] medir el "tiempo de búsqueda" para una palabra completa, compararlo con compressed_index
- [ ] medir el "tiempo de búsqueda" para una palabra parcial, compararlo con compressed_index
- [ ] estar seguros de la historia con respecto a threads (hoy ya hay una maquinaria del lado web que funciona, tenemos que ver que encaje ok)
- [ ] medir el tiempo de bootstrap (desde que decimos "cargate" hasta que se puede hacer la primer búsqueda), compararlo con compressed_index
- [ ] pensar qué optimizaciones extras se le puede hacer a SQLite por fuera de lo "default" (ejemplo, apagar transacciones o controles, porque nunca vamos a escribir...)

**Comment by facundobatista** [comment]
Este ya landeó todo.
