### ISSUE TITLE
Alternativa a pyinstaller para generar cdpedia.exe

### ISSUE THREAD

**Issue by fzuccolo** [PyAr/CDPedia#289]
La mayor desventaja de usar pyinstaller es que hay que regenerar `cdpedia.exe` en Windows cada vez que el código cambia. El último binario generado ocupa aprox. 10 MB. Estuve explorando una alternativa.

A partir de 3.5 hay disponible una distribución de python optimizada: https://docs.python.org/3/using/windows.html#the-embeddable-package

Es un zip de 7 MB, menos de 14 MB sin comprimir: https://www.python.org/downloads/release/python-385

Podríamos incluir este python en un directorio de la imagen y que `cdpedia.exe` funcione como un simple launcher que podemos hacer en C:

```c    
#include <windows.h>
    
int main(void)
{
    WinExec("pythondir\\python.exe cdpedia.py", SW_HIDE);
    return 0;
}
```
    
También podemos hacer algo más elaborado de ser necesario: https://docs.python.org/3/extending/embedding.html#very-high-level-embedding

Con estos cambios no haría falta regenerar nada cuando el código se modifica: al *exe* una vez compilado en Windows no habría que tocarlo y en caso de necesitar actualizar la versión de python es descargar y descomprimir un zip.
Lo probé con la versión 3.8.5 y funciona bien, tanto desde un directorio como desde una ISO.

**Comment by facundobatista** [comment]
Seria este enlace al zip en cuestión, no? https://www.python.org/ftp/python/3.8.5/python-3.8.5-embed-win32.zip

**Comment by facundobatista** [comment]
Entonces, según charlamos ayer... la idea es meter este zip descomprimido en la CDPedia, bajar una versión estable (podemos agarrar 3.8.5 *ahora* y listo, no hace falta hacerlo 3 días antes), y que el "autorun" ejecute eso el `cdpedia.py` usando eso, no?

También hay que hacer algún `cdpedia.bat` que sea lo que la gente va y le hace doble-click (porque ya no tendríamos un `cdpedia.exe`.

Hay que poner todo esto en el directorio `resources/autorun.win/`, y ajustar el LEANME.txt que hay ahí.

¿Falta algo o con eso estamos?

**Comment by fzuccolo** [comment]
> Seria este enlace al zip en cuestión, no?  https://www.python.org/ftp/python/3.8.5/python-3.8.5-embed-win32.zip

Sí, ese mismo.

> ¿Falta algo o con eso estamos?

Con eso y 2 líneas en `generate.py` para descomprimir el zip a cdroot ya estamos.
