### ISSUE TITLE
Dejar de copiar los css a mano

### ISSUE THREAD

**Issue by laureanoSilva** [PyAr/CDPedia#294]
Estamos descargando los css a mano, y wikipedia tiene cada vez hojas de estilo. Hay que pasar a hacerlo desde el scraper.

**Comment by fzuccolo** [comment]
@spiccinini  Muy buena la prueba [preprocess_stylesheets][1]! Me parece que es lo que hay que hacer.
Dejarlo como un script a ejecutar manualmente me parece bien para 0.9.

Dejo algunas observaciones:

### 1. Extracción de URLs

Algunas URLs dentro de los CSS tienen paréntesis y la regex actual falla en la extracción en esos casos y deja el CSS roto, haciendo que algunos elementos se muestren mal (por ej. las InfoBox).

https://github.com/PyAr/CDPedia/blob/595c174786fddbdd0c1ced3776766c0108aa6eea/src/preprocess_stylesheets.py#L98

Por ej. originalmente tenemos:

```
{background:url("//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Donkey_(71167)_-_The_Noun_Project.svg/40px-Donkey_(71167)_-_The_Noun_Project.svg.png") no-repeat right top}
```

Y luego de la extracción queda:

```
{background:url(nofile)_-_The_Noun_Project.svg/40px-Donkey_(71167)_-_The_Noun_Project.svg.png") no-repeat right top}
```

Una opción podría ser cambiar la regex por `url\(([^\s}]*)\)`.


### 2. El footer no se muestra correctamente

<kbd><img src="https://user-images.githubusercontent.com/61316398/92780493-a438ce00-f379-11ea-87c0-bcd1901739a2.png" width="500px"></kbd>

Habría que agregarle `class="mw-footer"` a `<div id="footer">` en el template para que se muestre bien.

https://github.com/PyAr/CDPedia/blob/595c174786fddbdd0c1ced3776766c0108aa6eea/src/web/templates/cdpedia_base.html#L40


<kbd><img src="https://user-images.githubusercontent.com/61316398/92780883-042f7480-f37a-11ea-81c4-44685d2bdba3.png" width="500px"></kbd>

### 3. Ubicación de los archivos

Como las imágenes son de wikimedia e independientes del idioma, en el proyecto podríamos tener:

```
resources/static/css/
├── assets/
├── wikipedia_es.css
├── wikipedia_gn.css
│   ...
└── cdpedia.css
```

y cuando copiemos lo que corresponda en cdroot quedaría:

```
cdpedia/assets/static/css/
├── assets/
├── wikipedia.css
└── cdpedia.css
```

[1]: https://github.com/PyAr/CDPedia/tree/preprocess_stylesheets

### 4. Un grado más de complejidad

Los CSS son dinámicos y dependen de los **módulos** que cada artículo pide. Cada módulo agrega diferentes reglas. La URL general de los CSS es:

```
https://es.wikipedia.org/w/load.php?lang=es&modules=...&only=styles&skin=vector
```

Por ej. con el primer CSS de la portada se solicitan estos módulos:

```
modules=ext.uls.interlanguage|ext.visualEditor.desktopArticleTarget.noscript|ext.wikimediaBadges|jquery.makeCollapsible.styles|mediawiki.ui.button|skins.vector.styles.legacy
```

Y con el primer CSS del artículo Argentina:

```
modules=ext.cite.styles|ext.tmh.thumbnail.styles|ext.uls.interlanguage|ext.visualEditor.desktopArticleTarget.noscript|ext.wikimediaBadges|jquery.tablesorter.styles|mediawiki.page.gallery.styles|mediawiki.toc.styles|skins.vector.styles.legacy|wikibase.client.init
```

Para Argentina se pide el módulo `mediawiki.page.gallery.styles` que se encarga de mostrar correctamente las galerías de imágenes, pero no se pide para la portada. Como a esas reglas no las estamos incluyendo ahora en CDPedia, las galerías de imágenes se verán *mal*.

Hay muchos módulos que no estamos descargando. Lo ideal sería encontrar una lista y descargarlos a todos. O utilizar otra página que solicite más módulos para que los CSS que descarguemos sean más completos.

**Comment by spiccinini** [comment]
@fzuccolo Excelente el review del branch!!! Muy buenas indagaciones y documentado.
Le voy a dar una vuelta de rosca el finde para arreglar esas cosas que decis y dejar un poco mas presentable el script de descarga que tiene algunas cosas hardcodeadas y/o hechas medio rapido.

**Comment by fzuccolo** [comment]
Dejo documentada una opción explorada y descartada:

Se puede obtener una lista de todos los módulos CSS que *podría* estar usando una wikipedia analizando el código fuente de MediaWiki, más precisamente el archivo [`Resources.php`][1] y cada una de las [extensiones disponibles][2]. Una primera exploración arrojó más de 800 módulos CSS diferentes, muchos provenientes de extensiones.

Como no tenemos forma de saber qué extensiones estan activas en las wikis que nos interesan, no me pareció una buena opción meter todo ese CSS en CDPedia, ya que la mayoría de las reglas quedarían sin usar.

[1]: https://github.com/wikimedia/mediawiki/blob/master/resources/Resources.php
[2]: https://github.com/wikimedia/mediawiki-extensions
