### ISSUE TITLE
Remove hardcoded 'es' language from URL string

### ISSUE THREAD

**Issue by fzuccolo** [PyAr/CDPedia#357]
URL should be built using `config.LANGUAGE`

https://github.com/PyAr/CDPedia/blob/c073ff7e3691296e9d50ed3175317cce1d4abf66/src/images/extract.py#L219-L220

**Comment by y-martinez** [comment]
Hi @fzuccolo I am a GSoC aspirant and I would like to apply this year with the project PyZombies, however, I would like to contribute to other projects of PyAr to support my proposal, so I saw this issue open, this available? seems to be a simple issue so I would like to work on this

**Comment by fzuccolo** [comment]
Hi @y-martinez, it's great to hear that you want to contribute to this project! Yes, this issue is available, I assigned it to you so you can work on it. Let me know if you have any questions!

**Comment by y-martinez** [comment]
@fzuccolo Ready the PR, I tried to link it to this issue using (Close or Resolve) and nothing so here is the PR [link]( https://github.com/PyAr/CDPedia/pull/373 )
