### ISSUE TITLE
Probar si PIL es mas rapido que fork+convert

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#40]
_From [alecura](https://code.google.com/u/alecura/) on December 19, 2009 14:37:36_

Todas las conversiones de imagenes se estan haciendo llamando a un proceso
externo.
Hay que probar si hacerlo en el mismo proceso de la conversion resulta mas
veloz.

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=39_

**Comment by gurupratap-matharu** [comment]
Hey I would like to contribute to this project.

To reduce the process time for images I

1. Installed the PIL package in my virtual environment
2. Wrote a new function called scaleImage that reduces the size the a % scale factor
3. Saves the resized image at the appropriate new path.
4. Logs an error incase the image is not found

This function is called in the main body where earlier the manual `convert` command was called.
`import Image

def scaleImage(frompath, topath, scale_factor):
    """
    Reduces the size ofan image by the scale_factor using the PIL library
    """
    scale_ratio = scale_factor / 100 # since scale_factor is in percentage
    try:
        im = Image.open(frompath)
    except IOError:
        logger.warning("Couldn't read image at %s" % frompath)
        return -1
    
    # pull out the original dimensions and calculate resized dimensions
    width, height = im.size 
    resize_tuple  = (width * scale_ratio, height * scale_ratio)
    
    # resize and save at new destination
    output_image = im.resize(resize_tuple)
    output_image.save(topath)
    logger.info("Success! Resized image saved at %s" % topath)
    
    return 0

.....

def run(verbose):
    ...
    # scale image using PIL
    status = scaleImage(frompath=frompath, topath=topath, scale_factor=escl)
                
`
It would be great if you can review the code and give me suggestions and authorize me for a pull request

**Comment by facundobatista** [comment]
Hello Gurupratap!

The whole point of this issue is to *measure* what is faster.

The idea would be to grab a good amount of real images from the wikipedia dump and process them (reducing some to 50%, some to 75%), using both mechanisms, and see how it behaves.

A script should be provided for benchmark reproducibility (be aware of cleaning disk caches between measurements!). 

Then we can make a decision.

Thanks!!!!

**Comment by tenuki** [comment]
> The whole point of this issue is to _measure_ what is faster.

In my opinion there are other things to consider too, some related to "process" and some related to "quality".

About process, I mean ease of setup and integration: in my personal opinion is that pil/pillow is easier to setup than requiring an external (to python) dependency. Also, image processing is easier to integrate con configure. (I'm saying that considering there is a lot of builds for all platforms for pillow).

About quality, we should consider not only speed but also compression/ratio and quality. For a project like this one, compression ratio (I think) is the priority.  I believe, pillow is based on the same libraries than imagemagik so probably they would perform approximately in the same way.

I think it would be necessary, however, to consider an extra "compression" step like #85 suggests.

**Comment by facundobatista** [comment]
Yes! We need to consider those other extras. However note that *a lot of time* is spent recoding these images, so if we get a 30% of speedup, let's go for that.

Or, if PIL is 30% slower, it's not a good idea.

If we get similar results +1 to PIL, it's just a Python dependency, not a system one!

Regarding the "extra compression" step, you say we may achieve this with Pillow itself? Thanks!
