### ISSUE TITLE
Crear actividad para Sugar

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#60]
_From [dmascialino](https://code.google.com/u/dmascialino/) on May 06, 2010 09:37:36_

Estaría bueno distribuir CDPedia en las XO.

Actualmente existe una actividad de wikipedia offline,
ver: http://wiki.laptop.org/go/WikiBrowse

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=59_

**Comment by facundobatista** [comment]
XOs are dead :/
