### ISSUE TITLE
Links y nombre en disco de imágenes feos

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#70]
_From [gringotu...@gmail.com](https://code.google.com/u/106902616802377880150/) on January 11, 2011 10:52:03_

Los nombres de las imágens se guardan en la forma original del link de wikipedia.

link = urllib.quote(dsk_url.encode("latin-1"))

feo!

Para corregirlo:

Hay que buscar el lugar exacto donde se obtiene el nombre de la imágen y unquotearlo y codificarlo a utf.

Luego hay que cambiar la línea 265 de extrar.py:
        htm_url = '<img&#37;ssrc="&#37;s"&#37;s/>' &#37; (p1, urllib.quote(dsk_url.encode("latin-1")), p3)

a
        htm_url = '<img&#37;ssrc="&#37;s"&#37;s/>' &#37; (p1, dsk_url, p3)

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=69_

**Comment by facundobatista** [comment]
Estaría bueno revisar esto ahora, que quizás el formato cambió.

**Comment by NicolasSandoval** [comment]
Todo esto se encuentra actualizado!
Este es el ultimo PR con fixs sobre extract.py.
Simplificando extract.py y arreglando bugs #199

**Comment by facundobatista** [comment]
@NicolasSandoval entonces podemos cerrar este issue?
