### ISSUE TITLE
Correr pngcrush a los png

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#85]
_From [facundob...@gmail.com](https://code.google.com/u/113918106348664864973/) on March 23, 2011 13:31:21_

Esto nos daría un png más chico, sin perder calidad

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=84_

**Comment by tenuki** [comment]
Creo que tambien hay otros tools que estaria bueno intentar/aplicar:

 * pngnq
 * pngquant
 * trimage
 * optipng
 * advancecomp
 * jpegoptim

**Comment by facundobatista** [comment]
Qué parámetros tendríamos que medir con cada uno? Sólo tamaño final del archivo? U otras consideraciones?

**Comment by NicolasSandoval** [comment]
Despues de probar los optimizadores, se decide utilizar:

**Pillow,** para remover metadatos.	

- Logra un 18% aprox. de reduccion en formatos PNG, JPEG y GIF.

**Pngquant**, para optimizar las imagenes con formato PNG.

- Logra un %70 aprox. de reducción en el peso en las imágenes logrando una excelente calidad final con un mínimo cambio en los patrones de colores.

Las imágenes con formato JPEG se dejan como están, por tener perdida
en la calidad final y poca ganancia en la reducción de peso, menor a un 3% aprox.

Seguimos con la reducción de pixeles en las imágenes finales por
ser alto el nivel de peso que se reduce en las mismas.

**Comment by facundobatista** [comment]
Perfecto, lo seguimos en el nuevo que es la "implementación" de este análisis...
