### ISSUE TITLE
Medir distintos métodos de compresión/redimensión de imágenes

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#87]
_From [gaitan@gmail.com](https://code.google.com/u/gaitan@gmail.com/) on March 24, 2011 17:05:22_

Se necesita un script que mida la performance de compresión (y la calidad resultante) con diversos métodos para prepocesamiento de imágenes. 
- Medir el tamaño inicial 
- Aplicar proceso
- Medir tamaño resultante.

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=86_

**Comment by facundobatista** [comment]
Tenemos el #40 para evaluar tiempo de "reducción de imágenes a nivel píxeles" (que es lo que hacemos cuando incluimos las imágenes al 100%, 75% y 50%) y el #85 para evaluar formas de que la imagen, sin perder calidad, ocupe menos espacio.

No tiene sentido armar infrastructura para hacer eso.
