### ISSUE TITLE
Posible error, url en nombre de imagen.

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#91]
_From [verdumariano@gmail.com](https://code.google.com/u/verdumariano@gmail.com/) on March 24, 2011 19:17:37_

Buscando resolver el issue 69 encontré esta imagen:

http://localhost:8000/images/shared/http&#37;3A//bits.wikimedia.org/skins-1.17/common/images/magnify-clip.png

Donde debería ser:

http://localhost:8000/images/shared/SU-CATEGORIA/magnify-clip.png

Como por ejemplo lo cumple la siguiente:

http://localhost:8000/images/shared/thumb/0/0e/220px-Notation_accents1.png

---

Lo encontré en el post Acentuación (Música):

http://localhost:8000/wiki/Acentuaci&#37;C3&#37;B3n_(m&#37;C3&#37;BAsica)

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=90_

**Comment by facundobatista** [comment]
We should at least check this is fixed now

**Comment by facundobatista** [comment]
La página original cambió y ya no tenemos esto; tambien considerando que se debería haber corregido como dice el comentario arriba, cerremos.
