### ISSUE TITLE
El buscador no busca en las paginas institucionales

### ISSUE THREAD

**Issue by hugoruscitti** [PyAr/CDPedia#94]
_From [dmascialino](https://code.google.com/u/dmascialino/) on March 25, 2011 23:53:25_

Actualmente solo busca en lo artículos

_Original issue: http://code.google.com/p/cdpedia/issues/detail?id=93_

**Comment by facundobatista** [comment]
Todo lo que es resta es que tenemos que confirmar que al armar el índice estamos incluyendo tambien a las páginas que tienen un namespace.

**Comment by fzuccolo** [comment]
Esto no sucede actualmente. Probé buscando manualmente los namespaces y los resultado se muestran correctamente:

| Búsqueda | Primer resultado (página ok) |
| ------------- | ------------- |
|`ciencia`  | `Portal:Ciencia política`|
|`wikipedia` | `Wikipedia:Artículos buenos`|
|`ayuda` | `Ayuda:Enlace permanente`|
|`categoría` | `Categoría:Wikipedia:Portales`|
